# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GD <- function(beta_0, tau, X, Y, eta_0 = 1e-3, alpha = 2) {
    .Call(`_RGD_GD`, beta_0, tau, X, Y, eta_0, alpha)
}

runif_in_pball <- function(n, d, p, r = 1) {
    .Call(`_RGD_runif_in_pball`, n, d, p, r)
}

RGD <- function(X, Y, tau, iter, eta_0 = 1e-3, alpha = 2) {
    .Call(`_RGD_RGD`, X, Y, tau, iter, eta_0, alpha)
}

cplexcoef <- function(X, Y, tau) {
    .Call(`_RGD_cplexcoef`, X, Y, tau)
}

picksamples <- function(X, Y, n_ratio) {
    .Call(`_RGD_picksamples`, X, Y, n_ratio)
}

